version: "3"
services:
  pg:
    image: postgres:16.3
    # === DISABLED BY DEFAULT ===
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$PDPA_WDC_PG_PASSWORD
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1s
      timeout: 3s
      retries: 5
  pgrst:
    image: postgrest/postgrest
    ports:
      - 3000:3000
    environment:
      - PGRST_DB_URI=postgres://postgres:$PDPA_WDC_PG_PASSWORD@pg:5432/postgres
      - PGRST_DB_ANON_ROLE=webuser
      - PGRST_DB_AGGREGATES_ENABLED=True
    depends_on:
      pg:
        condition: service_healthy
  front-end:
    build:
      context: .
      args:
        - PUBLIC_PDPA_WDC_PGRST_ENDPOINT=$PUBLIC_PDPA_WDC_PGRST_ENDPOINT
    depends_on:
      - pgrst
    ports:
      - 80:80
